<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3umMPBGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3umMPBG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3umMPBG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'joke' => ['privates', '.errored..service_locator.3umMPBG.App\\Entity\\Joke', NULL, 'Cannot autowire service ".service_locator.3umMPBG": it references class "App\\Entity\\Joke" but no such service exists.'],
        ], [
            'joke' => 'App\\Entity\\Joke',
        ]);
    }
}
