<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U9O781Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U9O7_81' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U9O7_81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'joke' => ['privates', '.errored..service_locator.U9O7_81.App\\Entity\\Joke', NULL, 'Cannot autowire service ".service_locator.U9O7_81": it references class "App\\Entity\\Joke" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'joke' => 'App\\Entity\\Joke',
        ]);
    }
}
