<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FhU75UnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FhU75Un' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FhU75Un'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\JokeController::delete' => ['privates', '.service_locator.U9O7_81', 'get_ServiceLocator_U9O781Service', true],
            'App\\Controller\\JokeController::edit' => ['privates', '.service_locator.U9O7_81', 'get_ServiceLocator_U9O781Service', true],
            'App\\Controller\\JokeController::getRandomJoke' => ['privates', '.service_locator.Ye08Ir4', 'get_ServiceLocator_Ye08Ir4Service', true],
            'App\\Controller\\JokeController::newJoke' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\JokeController::show' => ['privates', '.service_locator.3umMPBG', 'get_ServiceLocator_3umMPBGService', true],
            'App\\Controller\\JokeController::showAll' => ['privates', '.service_locator.Ye08Ir4', 'get_ServiceLocator_Ye08Ir4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\JokeController:delete' => ['privates', '.service_locator.U9O7_81', 'get_ServiceLocator_U9O781Service', true],
            'App\\Controller\\JokeController:edit' => ['privates', '.service_locator.U9O7_81', 'get_ServiceLocator_U9O781Service', true],
            'App\\Controller\\JokeController:getRandomJoke' => ['privates', '.service_locator.Ye08Ir4', 'get_ServiceLocator_Ye08Ir4Service', true],
            'App\\Controller\\JokeController:newJoke' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\JokeController:show' => ['privates', '.service_locator.3umMPBG', 'get_ServiceLocator_3umMPBGService', true],
            'App\\Controller\\JokeController:showAll' => ['privates', '.service_locator.Ye08Ir4', 'get_ServiceLocator_Ye08Ir4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\JokeController::delete' => '?',
            'App\\Controller\\JokeController::edit' => '?',
            'App\\Controller\\JokeController::getRandomJoke' => '?',
            'App\\Controller\\JokeController::newJoke' => '?',
            'App\\Controller\\JokeController::show' => '?',
            'App\\Controller\\JokeController::showAll' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\JokeController:delete' => '?',
            'App\\Controller\\JokeController:edit' => '?',
            'App\\Controller\\JokeController:getRandomJoke' => '?',
            'App\\Controller\\JokeController:newJoke' => '?',
            'App\\Controller\\JokeController:show' => '?',
            'App\\Controller\\JokeController:showAll' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
