<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ye08Ir4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ye08Ir4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ye08Ir4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jokeRepository' => ['privates', 'App\\Repository\\JokeRepository', 'getJokeRepositoryService', true],
        ], [
            'jokeRepository' => 'App\\Repository\\JokeRepository',
        ]);
    }
}
