<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJokeRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\JokeRepository' shared autowired service.
     *
     * @return \App\Repository\JokeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JokeRepository'] = new \App\Repository\JokeRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
