<?php

namespace ContainerIxwsHyf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJoke2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.U9O7_81.App\Entity\Joke' shared service.
     *
     * @return \App\Entity\Joke
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.U9O7_81": it references class "App\\Entity\\Joke" but no such service exists.');
    }
}
