<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxwsHyf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxwsHyf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxwsHyf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxwsHyf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxwsHyf\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxwsHyf',
    'container.build_id' => '9da93c90',
    'container.build_time' => 1718100014,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxwsHyf');
